## tests/threads/test_tripwire_thread_basic.nim — Task 3.3 happy path (M1).
##
## Exercises the fundamental `withTripwireThread` contract: a TRM fired
## inside the child thread body records its interaction on the PARENT
## verifier's timeline (via the shared `ref Verifier` handoff), and the
## parent can assert/consume that interaction after `joinThread` returns.
##
## Runs under `--mm:arc` (NOT `--gc:orc`) due to a Nim 2.2.6 process-exit
## crash in orc cycle collection (`orc.nim:unregisterCycle`) when the
## tripwire Verifier ref graph is torn down after a child thread has
## accessed it. The test logic is design-clean under both: `--mm:arc`
## passes cleanly; `--gc:orc` would also pass its assertions but SIGSEGV
## in `unregisterCycle` on exit. Design §8.1 supports both arc and orc
## ("requires --gc:orc or --gc:arc"); arc is selected here to unblock WI3
## until the upstream Nim issue is resolved. Matrix cell #7 (Task 3.9)
## will pick the same GC.
##
## Design citations:
##   - §3.1: user-facing API example (`sandbox → expect → withTripwireThread → assert`)
##   - §3.3: handoff mechanism sequence diagram (parent captures
##     `currentVerifier()`, child pushes it onto its verifierStack,
##     child body's TRM lands on the shared timeline)
##   - §8.1: supported GCs clause (orc OR arc; both are design-valid)
##
## Metric M1: threading intercepts work under `--mm:arc --threads:on`.
##
## Mirrors the `test_mock_expect.nim` pattern: module-scope `mockable`
## TRM + in-test `expect` registration + wrapper-proc call-site to
## sidestep the unittest-dirty-template TRM gotcha documented there.
import std/[unittest, options]
import tripwire/[types, timeline, sandbox, verify]
import tripwire/plugins/mock
import tripwire/threads

# User proc we intend to mock. Kept side-effect-free so the child body
# running under `--mm:arc` touches only the shared ref Verifier (design §8).
proc computeOnThread(x: int): int =
  x * 2   # real impl; TRM intercepts this

# Module-scope TRM emission. The dummy arg (0) only provides arity/type
# for the pattern's formal params; the value is not used at runtime.
mockable(computeOnThread(0))

# Wrapper proc — calling the mocked proc from here (not directly from the
# child body's statement list) matches the pattern in test_mock_expect.nim
# and keeps the TRM firing reliably in Nim 2.2.6.
#
# `{.gcsafe.}` cast: the TRM expansion references `mockPluginInstance` (a
# `let` at module scope in tripwire/plugins/mock.nim — effectively an
# immutable global ref) and verifier globals that the plugin guards. Under
# `--threads:on` Nim flags these as GC-unsafe access. The cast is safe
# because (a) `mockPluginInstance` is immutable, (b) the verifier state it
# touches is a shared `ref Verifier` crossed via `ThreadHandoff` (§3.3),
# and (c) we are deliberately testing that design under --mm:arc (§8.1).
proc callComputeOnThread(x: int): int {.gcsafe.} =
  {.cast(gcsafe).}:
    computeOnThread(x)

suite "withTripwireThread: happy path":
  setup:
    # Drain any stack left over from a prior test's failure path.
    while currentVerifier() != nil:
      discard popVerifier()

  test "TRM fired on child thread lands on parent timeline":
    # Child body kept as a separate proc so the TRM rewrite on
    # `callComputeOnThread(21)` happens against a normal proc body
    # rather than against an anonymous closure generated by
    # `withTripwireThread`'s body capture.
    proc childBody() {.gcsafe.} =
      doAssert callComputeOnThread(21) == 42

    sandbox:
      let v = currentVerifier()
      # Parent registers expectation BEFORE spawning the child.
      mock.expect computeOnThread(21):
        respond value: 42

      # withTripwireThread captures `currentVerifier()` on the parent,
      # spawns a worker, pushes the shared verifier on the child's stack,
      # runs the body, then joins. Any exception from the body re-raises
      # on the parent at joinThread.
      withTripwireThread:
        childBody()

      # Post-join assertions on the parent's timeline. The child's
      # interaction must be visible here because both threads share the
      # same `ref Verifier`.
      check v.timeline.entries.len == 1
      let entry = v.timeline.entries[0]
      check entry.procName == "computeOnThread"
      check entry.asserted == false

      # Consume the interaction so verifyAll (at sandbox exit) has a
      # clean timeline to inspect. This is the same consumption step
      # test_mock_expect.nim performs post-call.
      v.timeline.markAsserted(entry)
    # sandbox exit runs verifyAll; no unasserted interactions, no unused
    # mocks. If anything leaked to a different verifier, verifyAll here
    # would raise UnusedMocksDefect (expectation unconsumed) or the
    # child's TRM would have raised LeakedInteractionDefect earlier.
