## tests/threads/test_tripwire_thread_multi.nim — Task 3.4 sequential
## multi-child pattern (Metric M1, design §3.5).
##
## Exercises the "blessed multi-child" topology from v0.2 design §3.5
## (lines 409-427): TWO back-to-back `withTripwireThread` blocks inside
## ONE `sandbox` run, each child spawning, running, and joining strictly
## BEFORE the next child is spawned. Each child's TRM interaction lands
## on the shared parent verifier's timeline; `verifyAll` at sandbox exit
## sees all mocks consumed and all interactions asserted.
##
## Sequential, NOT concurrent. Design §3.5 explicitly scopes the v0.2
## guarantee to join-before-next-spawn: concurrent-spawn semantics are
## an explicit non-goal.
##
## Compile (mirrors test_tripwire_thread_basic.nim's arc rationale):
##
##   nim c --threads:on --mm:arc -d:tripwireActive \
##         --import:tripwire/auto -r tests/threads/test_tripwire_thread_multi.nim
##
## `--mm:arc` (NOT `--gc:orc`) because Nim 2.2.6's orc cycle collector
## crashes during ref-Verifier teardown after a child thread has pushed/
## popped the shared verifier. See `spike/threads/v02_gc_safety_REPORT.md`
## (Addendum) and test_tripwire_thread_basic.nim's header for the full
## reproducer. Design §8.1 lists orc and arc as co-equal supported GCs.
##
## Design citations:
##   - §3.5 (lines 409-427): "blessed multi-child" sequential pattern.
##   - §3.3: handoff mechanism — both children push the SAME parent
##     verifier onto their respective thread-local verifierStacks; both
##     TRM interactions therefore land on the one shared timeline.
##
## Metric M1: threading intercepts work under `--mm:arc --threads:on`.
##
## Mirrors `test_tripwire_thread_basic.nim`'s structure: module-scope
## `mockable`, a `{.gcsafe.}`-cast wrapper proc, and drain-verifier-stack
## in `setup`.
import std/[unittest, options, tables]
import tripwire/[types, timeline, sandbox, verify]
import tripwire/plugins/mock
import tripwire/threads

# User proc to be mocked. Two-arg form matches design §3.5's
# `computeThing(2, 3)` / `computeThing(4, 5)` example.
proc computeThing(x, y: int): int =
  x + y   # real impl; TRM intercepts this

# Module-scope TRM emission. The dummy args (0, 0) only provide arity
# and types for the TRM's formal params.
mockable(computeThing(0, 0))

# Wrapper proc — matches the basic test's {.gcsafe.}-cast pattern. The
# cast is safe for the same reasons documented there: `mockPluginInstance`
# is an immutable module-scope let, verifier state is a shared ref crossed
# via ThreadHandoff (§3.3), and this test is the design's intended
# --mm:arc exercise (§8.1).
proc callComputeThing(x, y: int): int {.gcsafe.} =
  {.cast(gcsafe).}:
    computeThing(x, y)

# Higher-order proc each child wraps around the mocked call. Mirrors the
# design §3.5 `someHigherFunction` that returns `mockedValue + 1`.
proc higherFunction(x, y: int): int {.gcsafe.} =
  callComputeThing(x, y) + 1

suite "withTripwireThread: sequential multi-child":
  setup:
    # Drain any stack left over from a prior test's failure path.
    while currentVerifier() != nil:
      discard popVerifier()

  test "two back-to-back children share parent timeline":
    # Child bodies kept as separate procs so the TRM rewrite of the
    # `computeThing(x, y)` call site inside `callComputeThing`'s body
    # executes in a normal proc context rather than inside the anonymous
    # closure generated by `withTripwireThread`'s body capture.
    # (See basic-test header for the full rationale.)
    proc firstChildBody() {.gcsafe.} =
      doAssert higherFunction(2, 3) == 43   # mock returns 42, +1 = 43

    proc secondChildBody() {.gcsafe.} =
      doAssert higherFunction(4, 5) == 91   # mock returns 90, +1 = 91

    sandbox:
      let v = currentVerifier()

      # Parent registers BOTH expectations BEFORE spawning ANY child.
      # Design §3.5's "blessed" ordering: sandbox -> expect* -> (spawn ->
      # join)* -> verifyAll. The parent must not mutate the verifier
      # (including registering new mocks) while a child is running.
      mock.expect computeThing(2, 3):
        respond value: 42
      mock.expect computeThing(4, 5):
        respond value: 90

      # First child: spawn, run, join. The child pushes the shared
      # verifier onto its thread-local stack, fires its TRM (which
      # consumes the computeThing(2, 3) mock and records an Interaction
      # on v.timeline), and re-raises any body exception to the parent
      # at joinThread.
      withTripwireThread:
        firstChildBody()

      # Second child: spawn, run, join AFTER the first has fully joined.
      # §3.5's sequential topology — parent mutates verifier state
      # (implicitly, by joining) only between children, never concurrently.
      withTripwireThread:
        secondChildBody()

      # Post-join assertions on the parent's timeline. Both children's
      # interactions must be visible here because both shared the same
      # `ref Verifier`. Order is insertion order (sequence-numbered).
      check v.timeline.entries.len == 2

      let firstEntry = v.timeline.entries[0]
      check firstEntry.procName == "computeThing"
      check firstEntry.asserted == false
      check firstEntry.args[".fp"] ==
        fingerprintOf("computeThing", @[$2, $3])

      let secondEntry = v.timeline.entries[1]
      check secondEntry.procName == "computeThing"
      check secondEntry.asserted == false
      check secondEntry.args[".fp"] ==
        fingerprintOf("computeThing", @[$4, $5])

      # Consume BOTH interactions so verifyAll (at sandbox exit) sees a
      # fully-asserted timeline and fully-consumed mock queue.
      v.timeline.markAsserted(firstEntry)
      v.timeline.markAsserted(secondEntry)
    # sandbox exit runs verifyAll: zero unasserted interactions, zero
    # unused mocks. If either child's TRM had landed on a DIFFERENT
    # verifier (handoff bug), verifyAll would raise UnusedMocksDefect
    # here (the expectations would never have been consumed), or the
    # child would have raised LeakedInteractionDefect earlier.
